### ISSUE TITLE
「犀」類字形的取碼方針？

### ISSUE THREAD

**Issue by danny0838** [Arthurmcarthur/Cangjie3-Plus#13]
「犀」的三代官方取碼只有「尸卜卜手」；若拆成「尸水竹手」需要用到五代新增的輔助字形，三代用此拆法有爭議。

目前編碼表中「犀」字拆「尸卜卜手」、「尸水竹手」，「屬」字可拆「尸卜卜戈」、「尸水田戈」，「樨」字只拆「木尸水手」。「部件字形支持」文件則未將「犀」字列入。

請問目前對此類字形的處理方針是什麼？

**Comment by Arthurmcarthur** [comment]
「犀」等字當初應是用了「二丨二」的字形，若用中間寫成「氺」的字形即使是三代也應能取到「尸水竹手」。「樨」字可能是之前做的有遗漏，目前我自己用的已经有了「木尸卜手」和「木尸水手」，但還沒有上傳。

**Comment by danny0838** [comment]
「卜卜」應該是取「丶丶丨丶丶」的字形。如果是「二丨二」的字形，中間應拆成「一一」。至於水的輔助字形是中間有鉤，但「犀」中間沒鉤，適用上有爭議。

如果要兼容所有異體，那至少會有「尸卜卜手」「尸一一手」「尸水竹手」三種拆法。

**Comment by Arthurmcarthur** [comment]
並非如此。五代之所以改碼，就是因為增加了「二丨二」的輔助字形。如果是像你說的，那五代增加的字形就是「⺀丨⺀」，「雨」也要改碼「一水月」。然而目前〇三五代「雨」同時有「一水月」和「一中月卜」，說明「⺀丨⺀」並未被增為五代的輔助字形，那五代增加的輔助字形只能是「二丨二」，由此得出原三代取的是「二丨二」的字形。

**Comment by danny0838** [comment]
代手冊有提到重新依標準字形取碼，因此五代與三代取碼所據字形不同。你可以參考維基教科書三五代編碼差異一節的附圖。

**Comment by Arthurmcarthur** [comment]
那麼請你看看五代手冊，「屬」的改碼理由是「增加輔助字形，方便取碼」。
短橫和「次」的類長橫是不同的，倉頡還有個隱藏的輔助字形，是兩個小短撇在「卜」上，用於「癶」等字，但是這個輔助字形也不能用在「形」等含長撇的字上啊。
