### ISSUE TITLE
「𠂁」如何取碼？

### ISSUE THREAD

**Issue by danny0838** [Arthurmcarthur/Cangjie3-Plus#14]
「𠂁」目前取「中中一卜」。

五代倉頡取碼「尸中戈」，按此精神似乎應取「卜卜中戈」或「卜中卜」？

**Comment by Arthurmcarthur** [comment]
前二碼不能取「卜」，不然「后」等字也要改碼了。
詢問官方後知「斉」在三代取「卜大中一中」，那此字取「中一卜中」或「中一戈中」。

**Comment by danny0838** [comment]
瞭解。那要採用何種編碼？或兼容兩者？

**Comment by Arthurmcarthur** [comment]
兼容兩者。
