### ISSUE TITLE
「汞」視為連體或分體字？

### ISSUE THREAD

**Issue by danny0838** [Arthurmcarthur/Cangjie3-Plus#16]
「𧋔」目前編作「一水.中一戈」，但是否應拆成「一.水.中戈」？

**Comment by danny0838** [comment]
發錯地方，自刪

**Comment by Arthurmcarthur** [comment]
手冊附錄並沒有說「汞」是分是連，只有一個不甚清晰的字形，漢文庫典也沒有找到相關字例。比照「泉」、「阜」等字，我認為「汞」作分體較恰當。
