### ISSUE TITLE
「言」是否視為特殊字首？

### ISSUE THREAD

**Issue by danny0838** [Arthurmcarthur/Cangjie3-Plus#17]
在[五代倉頡](https://github.com/Jackchows/Cangjie5/issues/103)，官方把「誩」拆作「卜口.卜一口」、「譶」拆作「卜口.卜口口」，而非比照把「順」拆成「中.中.中金」（而非「中中.一月金」）、把「靐」拆成「一月.田.一田」而非「一田.一田.田」的一貫切法。

但我們都知道，五代倉頡把很多字視為特殊字首的取法是有爭議的（例如「春」、「秦」、「冬」、「薛」、「登」等），官方未編碼的「𧮣」也因此有取作「月金.卜卜.口」或「月金.卜口.口」的爭議。不曉得官方三代倉頡如何看待「言」的拆法？按倉三原則應「一刀切」？或是「把言視為一單位切」？或是兼容二者？

**Comment by Arthurmcarthur** [comment]
「言」不是複合字首，不然「悥」也要改碼了。〇三五代碼表改自六代，所以有很多六代遺留。六代有一條規則是疊字要把成塊的字劃成字首，像「龘」要取「卜心卜心心」。「譶」取「卜口卜口口」就是因為官方疏忽，忘記把「譶」改成「卜一一口」。但是本碼表為了方便起見，也可以用「卜口卜口口」等方法輸入三疊字。

至於你說的「𧮣」字，取「月金卜口口」較好。倉頡劃分字首字身在這種情況下也是要看我們對漢字的認知的。像「澀」字，標準寫法是寫完「氵」後再寫「刃刃」，再寫「止止」，所以倉頡就取「水.尸戈.一」或「水.尸竹.一」。而像「競」字，標準寫法是「竞」、「竞」，所以倉頡也是從左到右劃成「卜山. 卜廿山」，而不是划成「卜廿.口山.山」。「𧮣」字，先從上把兩個「貝」劃走，然後下部的兩個言，書寫時顯然要寫成「言言」，所以「言」是次字首。

不過，「麗」、「䨻」這種字，因為上方的形塊都可一刀切出「一一」、「雨雨」，所以儘管這不符合我們的認知，也只好違反這種認知，取「一一月月心」、「一月田田田」。

**Comment by danny0838** [comment]
瞭解。我同意「𧮣」字維持原先「月金卜口口」取法，「言」類字按一般切法，但三疊、四疊字另設兼容碼。

> 〇三五代碼表改自六代，所以有很多六代遺留。六代有一條規則是疊字要把成塊的字劃成字首，像「龘」要取「卜心卜心心」。「譶」取「卜口卜口口」就是因為官方疏忽，忘記把「譶」改成「卜一一口」。

我沒查到六代有所謂的疊字規則，不曉得出自哪裡？「譶」取「卜口卜口口」是由於官方疏忽之說是官方承認過或只是猜測？有沒有相關來源？

沒別的意思，只是做個確認，畢竟這樣說等於否認漢文庫典反映了真正的五倉規則。很多官方取碼也因此要重新考慮是否不符五倉規則了。

**Comment by Arthurmcarthur** [comment]
通過一些官方文檔和六代對各種三疊字的取碼就可明白六代的三疊字規則。
漢文庫典中的「譶」字是漏改而已，像「鱻」等字都是符合取碼規則的。
