### ISSUE TITLE
反字與倒字的取碼？

### ISSUE THREAD

**Issue by danny0838** [Arthurmcarthur/Cangjie3-Plus#18]
最近的改碼似乎有改動「imirz  𢨋」「rauz   𨙨」等字，但過去「𨙨」都是取「rau」（即把反「乚」視為「山」的輔助字形），看log說是和官方交流過，可否說明下具體取碼原則？或公布當時的信件內容？

**Comment by mrhso** [comment]
镜像字加「片」。

**Comment by Arthurmcarthur** [comment]
第一次問官方，我舉了「𧹂」「𧥑」等上下鏡像字，問官方怎麼取碼。官方回答，可仿效六代以Z为結尾表示此類字。如六代有「𠄏」字就取「NNZ1」。
第二次問官方，主要是注意到左右鏡像字「𫸪」等，故又問官方能否用Z作結尾取這些字。官方回答稱可以。但是後來我又注意到「臦」、「𣥄」等字，若都應用Z來取，這些字要變動現有編碼，且六代沒有在「臦」上使用Z。因此對於此類左右鏡像字，我還會再詢問一次官方。

**Comment by danny0838** [comment]
1. 我查漢文庫典沒收「𠄏」字，請問該字的官方六代取碼是根據哪裡的資料？

2. 有官方使用「Z」為左右鏡像字編碼的實例嗎？

**Comment by Arthurmcarthur** [comment]
〇三五代沒有收這個字，要去翻官方PDF或使用圖片查詢。
目前沒有發現。

**Comment by danny0838** [comment]
所謂官方PDF是哪個PDF？

**Comment by Arthurmcarthur** [comment]
你若不相信，請訪問http://www.hanculture.com/m4/n/NNZ1.BMP
便可證實我的說法。

**Comment by mrhso** [comment]
这个官方 PDF 是朱邦复工作室私发给我们的，恕不能直接公开。
「仓颉笔记」有将此 PDF 文本化的计划。
我可以提供截图：
![image](https://user-images.githubusercontent.com/13294467/45923090-055a0380-bf0f-11e8-9a99-dfce3555fe83.png)
然后根据此 PDF 的字序，可以推断出此字在汉文库典的链接：
http://www.hanculture.com/dic/v.php?id=38628
我的意思，，，

**Comment by danny0838** [comment]
1. 漢文庫典和官方 PDF 的資料都是一致的嗎？

2. 官方有為「𢨋」、「𨙨」編過碼嗎？編什麼嗎？

**Comment by Arthurmcarthur** [comment]
是一致的。
官方没有收这两个字。

**Comment by danny0838** [comment]
所以目前「𨙨」取「rau」是已經定案了？還是你們會再向官方討論？

**Comment by Arthurmcarthur** [comment]
上下鏡像字使用Z取碼問題不大。而左右鏡像字還要再詢問一次。
