### ISSUE TITLE
相容區漢字編錯碼

### ISSUE THREAD

**Issue by danny0838** [Arthurmcarthur/Cangjie3-Plus#20]
https://zh.wikibooks.org/wiki/%E5%80%89%E9%A0%A1%E8%BC%B8%E5%85%A5%E6%B3%95/%E8%BC%94%E5%8A%A9%E5%AD%97%E5%BD%A2
「幵」系列左半邊變形都應該取j而非k。官方也沒取過k。

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L736
rmher

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L700
qbkf

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L495
hdhj

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L752
sjvit

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L512
hommn

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L814
wljka

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L401
hdhhh

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L701
pbtv

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L718
pgsk

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L462
eyii

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L711
dijc

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L702
dcrl

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1074
jiji

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1264
rqhk

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1379
vkuh

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1050
idhni

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1187
nue

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1222
pdwf

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1017
ihs

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L878
anau

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1392
bkkhu

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1020
hjsmm

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1045
hxvsf

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1116
lihmj

https://github.com/Arthurmcarthur/Cangjie3-Plus/blob/da7923070941ac5a93b48743b4043e009c3cede7/cj3_supplement.txt#L1179
(應刪除)

**Comment by Arthurmcarthur** [comment]
「幵」形字官方一律類推「一大一十」/「一十一十」兩字形。如「形」有「一大一十竹」和「一十一十竹」。
其他的，因為兼容區編碼時較為匆忙，後來也未及時校對，出了些錯，十分抱歉！

**Comment by danny0838** [comment]
五代補完說以下12字不算相容字，應按標準取碼處理：

    﨎﨏﨑﨓﨔﨟﨡﨣﨤﨧﨨﨩

https://github.com/Jackchows/Cangjie5/issues/129

**Comment by Arthurmcarthur** [comment]
我知道。當初我們已經就此事通過氣。

**Comment by danny0838** [comment]
但現在這些字還是列在 cj3_supplement.txt，有打算改嗎？

**Comment by Arthurmcarthur** [comment]
下次修改。

**Comment by mrhso** [comment]
不是「五代补完」说，而是 UCS 就是这么定义的，我们本来就和 IRG 有所联系的谢谢茄子。

**Comment by Arthurmcarthur** [comment]
已修正。
