### ISSUE TITLE
編碼誤植回報

### ISSUE THREAD

**Issue by TNTErick** [Arthurmcarthur/Cangjie3-Plus#26]
用到一半時偶然看到覺得一頭霧水的拆碼，
殅 有一弓(mn) 一弓竹手一(mnhqm) 㒳種編碼。

**Comment by TNTErick** [comment]
亇也記錯成弓弓。

**Comment by Arthurmcarthur** [comment]
殅編成「一弓」是微軟倉頡之誤，您可能誤用了微軟倉頡的碼表，或如果您使用了MSCJData，可能是您未用正確方式替換微軟倉頡的碼表。

「亇」確實編碼「弓弓」，先取「⺈」再取「亅」。

**Comment by TNTErick** [comment]
那麼𠲉和𠲏的編碼呢?
前者只有口人竹土，後者只有口人一土。

關於殅應該是我替換時的問題，我再去檢查看看。

**Comment by Arthurmcarthur** [comment]
「𠲉」的確只編了「口人竹土」，可能是因為編碼時Unicode文檔的字體，誤將下方的「壬」當成了「𡈼」，下次將補全。
「𠲏」字則有「口人竹土」和「口人一土」兩種編碼都有。

**Comment by Arthurmcarthur** [comment]
Fixed with commit fa078da68ffee4fdd69b00063848e82d0baa9302
