### ISSUE TITLE
Some questionable mappings

### ISSUE THREAD

**Issue by JLHwung** [Arthurmcarthur/Cangjie3-Plus#27]
| Character | Current | Expected | Note (for maintainer only) |
| --- | --- | --- | --- |
| `U+23388` [𣎈](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=23388) | awmf | **b**wmf |
| `U+2C0B2` [𬂲](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2C0B2) | emlm | **d**mlm |
| `U+2DAF6` [𭫶](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2DAF6) | eycb | **d**ycb |
| `U+2DAB1` [𭪱](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2DAB1) | eyid | **d**yid |
| `U+2146F` [𡑯](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2146F) | fomo | **g**omo |
| `U+2A002` [𪀂](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2A002) | hdvis | **hf**vis |
| `U+2EB25` [𮬥](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2EB25) | sfhn | **hf**hn |
| `U+2EB26` [𮬦](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2EB26) | sfmu | **hf**mu |
| `U+2E73F` [𮜿](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2E73F) | hhkni | **jj**kni |
| `U+2E517` [𮔗](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2E517) | ldbn | **li**dbn |
| `U+2AFF3` [𪿳](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2AFF3) | mtidd | **mr**idd |
| `U+2EAF9` [𮫹](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2EAF9) | nkleg | **nf**leg |
| `U+2B53B` [𫔻](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2B53B) | nkyk | **nl**yk |
| `U+2025F` [𠉟](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2025F) | pdhj | **o**dhj |
| `U+2D738` [𭜸](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2D738) | djkd | **p**jkd |
| `U+2D5E2` [𭗢](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2D5E2) | tkhk | **u**khk |

They are likely all typo in the key mappings.

Related: https://github.com/Jackchows/Cangjie5/issues/208

**Comment by Arthurmcarthur** [comment]
Thanks for your help. 
These problems will be fixed next time, but sadly I'm a little busy these days:( 
So it might take some times before I fix it:(

**Comment by JLHwung** [comment]
I can prepare a PR if you can review the expected mappings are correct. I am not familiar with Cangjie 3, they are derived by Cangjie 5 mappings.

**Comment by Arthurmcarthur** [comment]
Thank you. 
All of the mappings were correct except "U+2E517 𮔗", 
The correct Cangjie code for U+2E517 is "lidbn".
