### ISSUE TITLE
 請問此專案是否適於Windows11？

### ISSUE THREAD

**Issue by ZhaoMingLiu** [Arthurmcarthur/Cangjie3-Plus#39]
你好，
看到此專案圍繞開發在Windows10系統，
想知到目前是否支援比較新的作業系統（例：Windows11）？

**Comment by Arthurmcarthur** [comment]
您好，本專案並非圍繞Windows 10系統開發，主流系統都可以導入碼表。如果您詢問的是替換微軟倉頡碼表的文件，即MSCJData，它也是適用於Windows 11的。
